Introduce option for image expiration grace period.
metal-stack/metal-image-cache-sync pull request #5
Opened 2021-01-26 09:48 UTC by Gerrit91

Adds an option to still sync images even if they have already expired in the metal-api.

2021-01-26 12:00 UTC, majst01 requested changes
One small nit, otherwise LGTM

2021-01-26 12:00 UTC, majst01 commented on cmd/main.go
> +	rootCmd.Flags().Int("expiration-grace-period", 0, "the amount of days to still sync images even if they have already expired in the metal-api (defaults to zero)")
rootCmd.Flags().Uint will make the validation below obsolete

2021-01-26 12:00 UTC, majst01 commented on pkg/api/config.go
> +	if c.ExpirationGraceDays < 0 {
See comment above about Flags().Uint()

2021-01-27 09:24 UTC, Gerrit91 commented on cmd/main.go
> +	rootCmd.Flags().Int("expiration-grace-period", 0, "the amount of days to still sync images even if they have already expired in the metal-api (defaults to zero)")
Done. Thanks for review!

2021-01-27 09:28 UTC, majst01 approved these changes

2021-01-27 09:28 UTC, merged